const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const source=fs.readFileSync(path.join(__dirname,'../js/app.js'),'utf8');
function section(start,end){return source.slice(source.indexOf(start),source.indexOf(end,source.indexOf(start)));}
function model(save){const ctx={aventura:Array(5).fill({}),obtenerCantidadMisiones:()=>10,localStorage:{getItem:()=>JSON.stringify(save)}};vm.createContext(ctx);vm.runInContext(section('function obtenerProgresoMapa()', 'function abrirMapaAventura()'),ctx);return ctx;}
test('partida nueva: solo se puede empezar la primera misión',()=>{const c=model({});assert.equal(c.estadoMisionMapa(0,0),'actual');assert.equal(c.estadoMisionMapa(0,1),'bloqueada');for(let m=1;m<5;m++)assert.equal(c.estadoMisionMapa(m,0),'bloqueada');});
test('migra el avance existente sin desbloquear misiones futuras',()=>{const c=model({escenarioActual:2,misionActual:4});for(let m=0;m<2;m++)for(let i=0;i<10;i++)assert.equal(c.estadoMisionMapa(m,i),'completada');assert.equal(c.estadoMisionMapa(2,3),'completada');assert.equal(c.estadoMisionMapa(2,4),'actual');assert.equal(c.estadoMisionMapa(2,5),'bloqueada');assert.equal(c.estadoMisionMapa(3,0),'bloqueada');});
test('final de aventura permite repetir todas las misiones',()=>{const c=model({escenarioActual:4,misionActual:9,estadoFinalAzrak:'completo'});for(let m=0;m<5;m++)for(let i=0;i<10;i++)assert.equal(c.estadoMisionMapa(m,i),'completada');});
test('la repetición no guarda progreso ni recompensas remotas',()=>{let writes=0;const c={AventuraMapa:{repeticion:{}},modoPruebasActivo:false,monedas:100,localStorage:{setItem(){writes++;}},leerRecompensasMonedasPendientes(){throw Error('replay touched reward queue');}};vm.createContext(c);vm.runInContext(section('function guardarProgreso()', 'function cargarProgreso()')+section('function otorgarMonedas(', 'function confirmarRecompensasMonedasSincronizadas('),c);c.guardarProgreso();c.otorgarMonedas(10,'test');assert.equal(writes,0);});
test('completar una repetición vuelve al mapa sin avanzar el mundo',()=>{const c={AventuraMapa:{repeticion:{}},desafiosCompletados:2,obtenerCantidadDesafiosMision:()=>3,palabrasUsadasEnMision:[],historiaMisionPendiente:false,escenarioActual:0,misionActual:9};for(const name of ['detenerAmbiente','detenerAmbientePuente','detenerAmbienteCristal','detenerPortalMision','detenerAmbienteHojas','detenerTormenta','detenerNiebla','detenerMiradasLobos','detenerPresenciaBosque','detenerAranaBosque'])c[name]=()=>{};vm.createContext(c);vm.runInContext(section('function avanzarMision()', 'function actualizarJugador()'),c);c.avanzarMision();assert.equal(c.AventuraMapa.repeticion.completa,true);assert.equal(c.escenarioActual,0);assert.equal(c.misionActual,9);});
